- _data/nav_footer.yml
- _data/nav_main.yml
- _includes/branding.html
- _includes/footer.html
- _includes/header.html
- _includes/mobile-controls.html
- _includes/navigation.html
- _includes/search.html
- _sass/default.scss
- admin/config.yml
This PR implements the State Template [Full Width Navigation with Active Search](https://beta.template.webstandards.ca.gov/sample/navigation-full-width-utility.html) component for site navigation.
This PR also configures both the primary and footer navs as editable collections within the Netlify CMS.
Note that search functionality will be implemented as part of #9. This PR provides the HTML template upon which to build the search form.
> Full-width nav with search

- _config.yml
- _layouts/category.html
- admin/config.yml
- admin/index.html
- admin/widgets/index.js
- admin/widgets/shortid.js
- content/_actions/agencies.md
- content/_actions/email-signup.md
- content/_actions/epay.md
- content/_categories/eligibility-verification.md
- content/_categories/payment-services.md
- content/_categories/payment-validators.md
- content/_categories/payments.md
- content/index.md
- index.html
This PR builds out much of the content structures needed to enable content management via the Netlify CMS:
* Defining core collection types for categories, pages, navigation, etc.
* Custom widget to generate unique ID, used for relation fields (ensuring the relation is stable)
* Sample content based on current mocks
Subsequent PRs will implement site-wide design and content rendering.
Closes #4 
Closes #6 
Closes #7`
Blogging content management will be implemented in a separate PR.
> Content management

- _config.yml
- _data/authors.yml
- _includes/components/author.html
- _includes/components/date-badge.html
- _includes/scripts/moment.html
- _layouts/post.html
- _sass/components.scss
- _sass/content.scss
- _sass/main.scss
- admin/config.yml
- admin/editor/image-caption.js
- admin/editor/index.js
- admin/editor/pull-quote.js
- admin/editor/youtube.js
- admin/index.html
- content/_posts/2020-09-03-payments-101.md
Closes #3.
Closes #5.
Includes custom editor components for embedding Youtube videos, quotes w/attribution, and images with captions in blog posts.
> Implement blog capability and render posts

- _includes/scripts/mapbox.html
- _includes/scripts/script.html
- _includes/scripts/tag.html
- _sass/main.scss
- _sass/pages/providers.scss
- content/_actions/providers.md
- content/providers.html
- scripts/map.js
~Not ready for merge, just want a deploy preview 😄~
Pushing out as-is, revisiting complete page content/experience in upcoming work.
> Map prototype

- _includes/forms/subscribe.html
- _sass/forms.scss
- admin/config.yml
- content/_actions/return-home.md
- content/pages/subscribe.md
- scripts/forms/subscribe.js
Follow-up to #32 now that form is submitting correctly.
Confirmation message and target (via Action selector) are configurable in CMS.
> Form submission confirmation

- Gemfile
- Gemfile.lock
- _plugins/data_package.rb
- metadata/providers/glossary.csv
In a previous pull request we removed this feature and accidentally didn't readd it. I've moved it to the jekyll build process so that it happens locally and in the netlify build process.
> Re-adding the data package build process

- .editorconfig
- _config.yml
In a previous pull request I removed this file to clean up the application, but there's value in keeping this.
> Readding editorconfig file for a better developer experience

- index.html
https://github.com/cal-itp/transit-stop/issues/262
> Make sure the RFP content shows up on mobile

- contact.html
> Add links for vendors on Contact page

- _pages/about.md
- contracts.html
- index.html
- provider-map.html
---
Preview URL: https://deploy-preview-291--cal-itp-transit-stop.netlify.app/
Closes #285
Closes #287
/cc @aialvarado
/cc @harrisonpeck
> Make changes for RFP launch

- metadata/providers/providers.csv
Update DASH's name in our provider dataset
Closes #296﻿
> DASH to Los Angeles Department of Transportation

- index.html
Do not merge until @esquared415 gives approval.
Closes #307, closes #314
> Updates to homepage

- _data/contracts.yml
- contracts/index.html
- contracts/view.html
Do not merge until @esquared415 gives approval.
Closes #315
Closes #316
> Updates to contracts pages

- _sass/components/_footnotes.scss
- contracts/view.html
- scripts/contracts/footer.js
- scripts/smart-table.js
> Hide footnotes

- _pages/about.md
- _pages/glossary-of-key-terms.md
- contracts/index.html
- contracts/view.html
- index.html
> Multiple page wording updates

- README.md
Adds a small section to the README on how to get submodules.
> Add notes about Git submodules to README

- _layouts/default.html
- provider-map.html
- resources.html
Closes #330
Question for @thekaveman : is there a way for me to test that events are being sent to Google Analytics?
> Track resource downloads

- _includes/forms/confirm.html
- _includes/forms/indicates-required.html
- _includes/forms/input.html
- _includes/forms/label.html
- _includes/forms/netlify-honeypot.html
- _includes/forms/required-label.html
- _includes/forms/submit.html
- _includes/forms/textarea.html
- _layouts/default.html
- _sass/overrides/_forms.scss
- contact.html
- contactless-support.html
- scripts/forms.js
Closes #332.
Refactors the [Contact us](https://www.camobilitymarketplace.org/contact) form into a number of reusable Jekyll `include` elements, which are then used to build the new form.
> Contactless Support form, reusable components

- resources.html
This is for #337 (but doesn't close it entirely)
> Update Resources link for support form

- _data/contracts.yml
> Fix: update Elavon contract number

- _data/contracts.yml
> Chore: remove expired contract

- resources.html
> Chore: Add DGS 213 link/text to Resources

- .devcontainer/devcontainer.json
- netlify.toml
- src/_includes/amplitude-init.html
- src/_includes/newsletter-sign-up.html
- src/_layouts/default.html
- src/scripts/amplitude.js
Closes #356.
See the issue for more discussion / [details about the tracking plan](https://github.com/cal-itp/mobility-marketplace/issues/356#issuecomment-1215465160).
> Feat: Amplitude events tracking

- src/_layouts/default.html
> Feat: integrate with Hubspot live chat

- src/_includes/toc-and-content.html
- src/go-contactless.html
- src/how-to/go-contactless.html
closes #400 
- From https://www.camobilitymarketplace.org/go-contactless, GET STARTED button should take you to our guide (https://www.camobilitymarketplace.org/how-to/go-contactless)
- From https://www.camobilitymarketplace.org/how-to/go-contactless, replace GET STARTED button with a VIEW GUIDE button that should drop you down to the guide below (on same page)
- Update button text to be sentence case here https://www.camobilitymarketplace.org/go-contactless so that "Get Started" reads "Get started" and "Contact Us" reads "Contact us"
> Go Contactless: Nav updates

- src/_sass/overrides/_forms.scss
> Fix: Validation msg red with asterisks

- src/contracts/index.html
> Chore: Update Contracts landing with new intro text, FTA links

- src/_data/contracts.yml
- src/_data/how_to/get_connected.yml
- src/_includes/how_to/get_connected_plan_table.html
- src/_includes/how_to/get_connected_pricing_table.html
closes #461 
- All the requests from Marissa https://docs.google.com/document/d/1XLUM0EuFa9-A1icT3rySVEUfyZcohOB0D-NTpla8TtI/edit is now reflected in the code. Awaiting copy review from Erika.
- Copy: NOT YET EDITED. AWAITING EDITS FROM @esquared415 
- https://deploy-preview-465--cal-itp-mobility-marketplace.netlify.app/how-to/get-connected#what-is-firstnet
- https://deploy-preview-465--cal-itp-mobility-marketplace.netlify.app/contracts/view?contracts-filter-product=Data%20Plans
> Get Connected: add new content, update some content

- src/_data/how_to/get_connected.yml
- src/_includes/how_to/get_connected_pricing_table.html
> Get connected: copy updates

- src/_data/how_to/get_connected.yml
> Get Connected: Switch order of 2 questions

- src/_includes/alert.html
- src/_sass/_base.scss
- src/index.html
> Home page: Banner

- src/_sass/components/_header.scss
> Fix transparent navbar on medium screens

- src/_data/how_to/get_connected.yml
> Fix: FirstNet edits

- src/_includes/agencies.html
- src/_sass/pages/_go-contactless.scss
- src/go-contactless.html
- src/index.html
Closes #466 
Based off changes from #489
> Feat: Modernize Fleet section

- src/index.html
> Feat: homepage newsletter signup

- src/_sass/components/_newsletter.scss
Figured this out!!!! cc / @segacy1
> Fix: Move the newsletter asterisks

- _config.yml
closes #500 
- Adds one link to the nav
- Any CSS changes? No.
> For vendors: Add to nav

- src/_includes/alert.html
- src/index.html
> GTFS-RT RFP alert

- src/_data/contracts.yml
> Contracts: add Fiserv

- src/_includes/alert.html
- src/index.html
> GTFS Alert: Take down alert - IGNORE FOR NOW / MERGE on 2/20

- src/_includes/alert.html
- src/index.html
Reverts cal-itp/mobility-marketplace#526
> Revert "GTFS Alert: Take down alert - IGNORE FOR NOW / MERGE on 2/20"

- src/_includes/alert.html
- src/index.html
> GTFS Alert: Take down alert - MERGE on 2/20 5pm

- src/how-to/go-contactless.md
> Add section for non-CA agencies under MSAs

- src/how-to/go-contactless.md
> Update copy about MSA Cost Estimation Tool

- .devcontainer/postAttach.sh
> fix(pre-commit): configure git to install pre-commit

- .github/workflows/add-to-project-dependencies.yml
Similar to https://github.com/cal-itp/eligibility-server/pull/467
> Feat: add dependency PRs to project, set status/effort

- .devcontainer/postAttach.sh
Quick follow-up to #559, fix a small typo
> Fix: correct git safe directory

- _config.yml
- src/_sass/_variables.scss
- src/_sass/components/_header.scss
closes #609 
- Update the "hover" color on the nav dropdown
- Each link has 10px padding top and bottom
- Update to sentence case
- Updates the left-alignment to 25% from the left.
Note: This PR can be merged and ready to go whenever, does not depend on other GTFS-RT tickets.
> Nav dropdown refresh

- src/intro-gtfs-rt.html
> Fix: Filtered link

- .github/CODEOWNERS
Allow @cal-itp/web-review to review/approve content-related updates
> Allow web-review to approve content updates
