- _config.yml
- _includes/scripts/ga.html
- _includes/site/head.html
- netlify.toml
@calexity this PR adds the GA code you setup (thanks!)
Jekyll has the concept of build environments, which allows us to only include the tracking code when we're building for `production`. We could setup another GA for `development` if you thought that would be useful - but at least our primary account will only show "real" traffic.
Closes #20.
> Add Google Analytics

- scripts/providers/table.js
Sorting by the Provider name / URL column used the URL value, leading to some confusing results.
This PR fixes sort on that column by comparing the Provider names.
> Fix Providers table sort

- _config.yml
- docker-compose.yml
In a previous pull request I removed the docker-compose support to clean up the repository and now we want to add it back using the latest standards.
> Allow users to boot up docker-compose in order to access the site locally

- _layouts/default.html
- provider-map.html
Technically, this unique enough and small enough that it can just be added to the Default layout. Though, I'm not sure if we'd be finding more things to track and just do things on a per-page basis. At the moment, I'm abusing front matter to place all of our related Google function calls together in a single script tag.
Fixes #273
> Track downloads of Provider Data

- provider-map.html
Events were not being registered in Google Analytics, need to use the Universal Analytics syntax:
https://developers.google.com/analytics/devguides/collection/gtagjs/events
> fix(analytics): use gtag script instead of ga

- src/_data/contracts.yml
- src/contracts/index.html
- src/uploads/connectivity.svg
Closes #309
* I assumed we wanted a single table row, listing all 3 vendors
* I also assumed we needed to apply the "Only for CA transit agencies" footnote to the table row
* Made the _Contract_ column say "View Data Plans" instead of "View" for clarity
> Feat: add link to existing data plan contracts

- README.md
I was unable to get the app open on my machine today. I added this one line of instruction to be more explicit what server address to open in the browser. 
Please check to see if these instructions work for you on your machines.
> docs(README): add server address to instructions

- .gitignore
Having `**/.DS_Store` ignored in Git is a standard practice for Apple/Mac users.
I realize @thekaveman @angela-tran won't really be able to test this locally though 😅  It's here in benefits: https://github.com/cal-itp/benefits/blob/dev/.gitignore#L11
Reference:
https://stackoverflow.com/questions/18393498/gitignore-all-the-ds-store-files-in-every-folder-and-subfolder
https://en.wikipedia.org/wiki/.DS_Store
> chore(gitignore): ignore all .DS_Store files from Mac users

- src/_sass/_base.scss
- src/contracts/index.html
closes #376 
- Typography: Adds `.h4` class
- Typography change: Make the css better reflect the new Type guide on Figma. The font family for H1 - H3 is Raleway, and H4 and below is Poppins.
- Typography: Adds `.subtext` class to represent the `Highly recommended` type style, to be used with `<em>` or `<span>`
> Contracts page: Add blurb

- .devcontainer/compose.yml
- README.md
closes #397 
- Remove `ports` config from compose.yml
Thanks to @angela-tran for figuring this out!!!
- Run this app locally with the latest VS Code
- Rebuild + Reopen in Container
- Run Rake task
- When the rake task is complete, click PORTS in VS Code - the bubble should be green. `http://localhost:4000/` should open:
> Fix: Docker/VS Code issue

- src/_sass/_utilities.scss
- src/_sass/_variables.scss
- src/how-to/go-contactless.html
#407 
This PR removes the image from the Go Contactless (and for future pages with the same layouts), and replaces it with a new dark blue background color. This layout will be used on all future pages with this layout, like the upcoming new Get Connected page, in progress here: #406 
I wanted to separate this change out in its own PR, so it can go out faster.
Utilities:
- This PR adds new variables: `$dark-blue` for `#225173` and `$gray-1` for `#eeeeee`. These come from the [Figma board's Styleguide page](https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?node-id=3725%3A10998&t=hgCWHxVnkijRGsKR-0)
- And new corresponding utility styles: `.bg-dark-blue`, `.btn-dark-blue-inverted`
> Background color for Go Contactless page

- netlify.toml
- src/_data/contracts.yml
closes #402 
- Users who go to the Contracts page and click `NASPO` will be taken to https://www.camobilitymarketplace.org/how-to/get-connected
- Adds a Netlify redirect so people going to `/assets/Cal-ITP.MobilityMarketplace.DataPlans.NASPO.FirstNet.pdf` get redirected to `/how-to/get-connected`. Test here: https://deploy-preview-410--cal-itp-mobility-marketplace.netlify.app/assets/Cal-ITP.MobilityMarketplace.DataPlans.NASPO.FirstNet.pdf
> Replace and redirect NASPO pdf link with how-to/get-connected link

- README.md
> docs(readme): move Google Cloud instructions to README

- _config.yml
- src/_layouts/default.html
closes #417 
This PR is the code portion of #417. Further configuration from Analytics admin is required.
This PR takes care of the first item: `Collect event data by adding the Google tag to your web pages.`.
1. Ensure ID from the code matches that in GA Admin
2. After this PR is closed, go into GA Admin and check that events are coming in
> feat(analytics): update Google Analytics to v4

- src/_sass/_functions.scss
- src/_sass/index.scss
- src/_sass/overrides/_tables.scss
fixes #425 
- Brings back a Bootstrap Sass function `escape-svg` so that the `@escape-svg` works properly for the down/up arrows on the Provider Map
- Removes regression in the table header cell vertical center alignment, by specifying a fix for only the Contracts table
- Renames `breakpoints` file to be more generalized, to all `functions`
- Arrow display, vertical alignment of table header cells
- Vertical alignment of table header cells
- Vertical alignmenet of table header cells
> Fix: Provider map table

- src/_sass/overrides/_forms.scss
- src/contact.html
closes #435 
- After the form is submitted, make sure to *hide* the `I am a...` question.
- ⚠️ **Test this PR in Chrome** ⚠️ 
- This PR uses the CSS `:has` selector, which is not supported on Firefox yet, but is supported on Chrome, Edge and Safari. Firefox is only used by 2% of the global population. https://caniuse.com/#feat=css-has Firefox allows users to turn on an experimental flag to turn `has` support on, and full support seems to be coming soon though. (https://twitter.com/alexlehner42/status/1636409643416133633, https://bugzilla.mozilla.org/show_bug.cgi?id=1820835, https://phabricator.services.mozilla.com/D172019) For now, I am comfortable with this fix b/c the vast majority of MobiMart users use Chrome or Edge: https://analytics.google.com/analytics/web/#/p353734172/reports/explo …
> Fix: On confirmation page, hide all forms

- src/_data/how_to/get_connected.yml
Closes #473 
I uploaded the PDF from https://github.com/cal-itp/mobility-marketplace/issues/473#issuecomment-1731677403 to our storage bucket so the resource lives at `resources.calitp.org`.
> Refactor: replace link to Google Doc with PDF

- .github/resources/download_csv.sh
- .github/resources/process_providers.py
- .github/workflows/provider-map-jobs.yml
- README.md
An idiotic (but better than sed) workaround so that `bq` will not pollute our CSV file with a welcome message that is COMPLETELY ignored by `--quiet`, `--headless`, and every other flag that implies "silence unnecessary output."
see https://stackoverflow.com/q/73177304
> Add a better workaround so providers.csv isn't polluted

- .github/resources/download_csv.sh
Looking at PRs #538, #541, #513, and gang shows no rhyme or reason behind the order of the CSV file. This makes it annoying and impossible to see the diffs between each pull, so this PR sorts the providers by NTD ID.
**Note:** PR #541 has been corrected to be in sorted order
> Sort provider map query by NTD ID

- .github/workflows/provider-map-jobs.yml
Add the `pre-commit` Action to our provider job so that the generated files are formatted in the same commit after it touches them. This will prevent future empty PRs from being created when the only diff is a newline due to formatting, and our pre-commit makes a second commit "undoing" the lack of a newline in the generated code.
I left a comment in my changes, but I want to point out that we need to allow the pre-commit step to continue despite failure because it will always fail whenever it formats files. We don't care about it "failing" since it'll have fixed our files already anyway.
Closes #550
> Don't trigger empty PRs for Provider Map updates

- _config.yml
fixes #573 
There was a small bug in the menu code that was preventing the For Vendors link from being highlighted when you're on that page. The menu should highlight the current page you are on.
Branch Preview https://deploy-preview-575--cal-itp-mobility-marketplace.netlify.app/for-vendors
Production
> fix(nav): the for-vendors link can be set to current

- _config.yml
- src/_includes/alert.html
- src/index.html
Add Remix announcement banner as a configurable setting in `_config.yml` so that we no longer have to touch multiple files to had an announcement.
Closes #564
> Homepage announcements are now configured with _config.yml

- src/contracts/index.html
closes #602 
- Changes link to a new link
- Not part of this PR: DOT team will make sure the old link https://dot.ca.gov/cal-itp/california-minimum-general-transit-feed-specification-gtfs-guidelines redirects to https://dot.ca.gov/cal-itp/california-transit-data-guidelines
> Fix: GTFS link on Contracts page

- src/_data/contracts.yml
- src/contracts/view.html
closes #454 
- Add 3 contracts, in the GTFS category, and the GTFS-RT product
- Changes 1 sentence on the contracts page template, which affects all the contract pages.
> GTFS-RT: Add 3 contracts

- src/_data/contracts.yml
- src/contracts/index.html
- src/contracts/view.html
closes #625 
This PR addresses 2 specific changes on the contract filtered page:
- The `email us` link now will direct users to email `hello@calitp.org` with a subject line of `Questions about contract`
- The Product category is now called `GTFS-Realtime`, changed from `GTFS-RT`. This affects how the table is displayed, and the URL.
- Email us link: <img width="1511" alt="image" src="https://github.com/user-attachments/assets/b3447a57-2a21-4481-8860-952fc8e7db6a" />
- GTFS-Realtime name: <img width="1512" alt="image" src="https://github.com/user-attachments/assets/9e989fd2-ec62-4696-bc6e-894f2f3b25c3" />
> Fix: Contracts page fixes

- src/_data/contracts.yml
- src/contracts/index.html
- src/intro-gtfs-rt.html
fixes #629 
The official style for "GTFS Realtime" has no hyphen between the words.
We are removing "GTFS-Realtime" from the whole app.
and all links to this page have been updated.
> Contracts: no hyphen between GTFS and Realtime

- src/_data/contracts.yml
Hosting the NASPO Addendum file under [`resources.calitp.org/`](https://resources.calitp.org/mobility-marketplace/State.of.California_Amendment.1_Extension.2023-05.pdf)
target page: https://deploy-preview-641--cal-itp-mobility-marketplace.netlify.app/contracts/view?contracts-filter-product=Data%20Plans
closes #620
> Host NASPO Addendum under Cal-ITP domain

- src/how-to/GTFS-RT.md
closes #643 
closing https://github.com/cal-itp/calitp.org/issues/455
(The bug ticket was written in the wrong repo.)
Link should be `/contracts/view?contracts-filter-product=GTFS Realtime`, not `/contracts/view?contracts-filter-product=GTFS-Realtime`
> Fix: fix GTFS Realtime category link
